### ISSUE TITLE
How to configure mapping to generate<note>tags when converting Word to Dita

### ISSUE THREAD

**Issue by ydlmp** [oxygenxml/oxygen-batch-converter-addon#57]

**Comment by DunaMariusCosmin** [comment]
Hi,

You can configure the mapping to generate an element with a class attribute and then you can create a custom refactoring operation to post-process the resulting topics for converting these elements to note elements. 
You have more information about this case here: https://blog.oxygenxml.com/topics/migrating_word_to_dita_bdc/frequently_asked_questions.html#word-to-dita-frequently-asked-questions__how-to-configure-mapping-when-wanted-element-doest-exist-in-html

Best regards,
Cosmin
